# Jupytext configuration for arx-nid
# This pairs .ipynb notebooks with .py:percent text files

# Remove notebook metadata that causes unnecessary diffs
notebook_metadata_filter = "-all"

# Remove cell metadata except for tags  
cell_metadata_filter = "-all,tags"

# Default format for new text files
default_jupytext_formats = "ipynb,py:percent"
