stages:
  build-features:
    cmd: python scripts/create_test_data.py --num-flows 1000 --output data/processed/flows_v0.parquet
    deps:
    - scripts/create_test_data.py
    outs:
    - data/processed/flows_v0.parquet
    desc: "Generate synthetic flow data for testing (replace with zeek2parquet.py when PCAP data is available)"
    
  create-tensors:
    cmd: python scripts/create_tensors.py --input data/processed/flows_v0.parquet --output data/processed/tensor_v0.npy --window-size 5 --min-flow-length 2
    deps:
    - scripts/create_tensors.py
    - data/processed/flows_v0.parquet
    - arx_nid/features/transformers.py
    outs:
    - data/processed/tensor_v0.npy
    - data/processed/tensor_metadata_v0.parquet
    desc: "Generate time-series tensors for deep learning models"
