name: Data Management

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  data-validation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dvc[s3] requests tqdm
        
    - name: Configure DVC
      run: |
        dvc config core.no_scm true
        
    - name: Pull data from DVC remote
      run: |
        # Only pull if DVC files exist
        if [ -f .dvc/config ]; then
          echo "Pulling data from DVC remote..."
          dvc pull || echo "No data to pull or remote not accessible"
        else
          echo "No DVC configuration found"
        fi
        
    - name: Validate data manifest
      run: |
        python -c "
        import csv
        print('Validating data manifest...')
        with open('data/datasets.csv') as f:
            reader = csv.DictReader(f)
            datasets = list(reader)
            print(f'Found {len(datasets)} datasets in manifest')
            for ds in datasets:
                print(f'  - {ds[\"dataset\"]}: {ds[\"url\"]}')
        "
        
    - name: Check download scripts
      run: |
        echo "Checking download scripts..."
        for script in scripts/download_*.py; do
          if [ -f "$script" ]; then
            echo "✓ $script exists"
            python -m py_compile "$script"
          fi
        done
        
    - name: Validate data structure
      run: |
        echo "Validating data directory structure..."
        ls -la data/
        echo "Raw data directory:"
        ls -la data/raw/ || echo "No raw data directory yet"
        echo "Processed data directory:"
        ls -la data/processed/ || echo "No processed data directory yet"
